  <div class="hero-unit">
    <h1>Welcome to PolySleepers</h1>
    <p>PolySleepers is a social site for aggregating and sharing data from polyphasic sleep attempts. This website is open source, and built on Zend Framework version <?php echo \Zend\Version::VERSION ?>.</p>
    <p><a class="btn primary large" href="<?php echo $this->url('zfcuser/register') ?>">Sign up now &raquo;</a></p>
  </div>

  <div class="row">
    <div class="span6">
      <h2>Track your progress</h2>
        <p>Help encourage yourself and track your progess. Compare yourself to others attempting polyphasic sleep. Keep track of oversleeps, manage your sleeping schedule online, and more.</p>
      <p><a class="btn" href="#">Learn More &raquo;</a></p>

    </div>
    <div class="span5">
      <h2>Lorem Ipsum</h2>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse auctor sagittis elit, eu facilisis turpis fringilla id. Vestibulum orci turpis, facilisis a tristique commodo, placerat lacinia dolor. Phasellus id metus tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      <p><a class="btn" href="#">Learn More &raquo;</a></p>
   </div>
   <div class="span5">

     <h2>Help &amp; Support</h2>
     <p>If you need any help or support while adapting to polyphasic sleep, there are community sites such as <a href="http://trypolyphasic.com/">TryPolyphasic.com</a> and blogs of various polyphasic sleepers available online. Additionally, a handful of polyphasic sleepers are generally available to chat around the clock on the <a href="http://webchat.freenode.net/?channels=%23polyphasers">##polyphasers</a> channel on Freenode</a>. We'll be glad to chat with you, help you through your adaption period, and answer any questions you may have about our experiences.</p>
     <p><a class="btn" href="http://webchat.freenode.net/?channels=%23polyphasers">Chat with Us &raquo;</a></p>
   </div>
  </div>

